version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: warehouse_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      
      MYSQL_DATABASE: 'warehouse_db'
      
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
